=== mililk4/chain-registry/chain.schema.json
{
    "$id": "https://sikka.tech/chain.schema.json",
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "Cosmos Chain",
    "description": "Cosmos Chain.json is a metadata file that contains information about a cosmos sdk based chain.",
    "type": "object",
    "required": [
        "chain_name",
        "chain_id",
        "bech32_prefix"
    ],
    "properties": {
        "chain_name": {
            "type": "string"
        },
        "chain_id": {
            "type": "string"
        },
        "pretty_name": {
            "type": "string"
        },
        "status": {
            "enum": [
                "live",
                "upcoming",
                "killed"
            ]
        },
        "network_type": {
            "enum": [
                "mainnet",
                "testnet"
            ]
        },
        "bech32_prefix": {
            "type": "string"
        },
        "genesis": {
            "type": "string"
        },
        "daemon_name": {
            "type": "string"
        },
        "node_home": {
            "type": "string"
        },
        "key_algos": {
            "type": "string",
            "properties": {
                "type": "array",
                "items": {
                    "type": "string",
                    "enum": [
                        "secp256k1",
                        "ethsecp256k1",
                        "ed25519",
                        "sr25519"
                    ]
                },
                "uniqueItems": true
            }
        },
        "slip44": {
            "type": "number"
        },
        "codebase": {
            "type": "object",
            "required": [
                "git_repo",
                "version"
            ],
            "properties": {
                "git_repo": {
                    "type": "string",
                    "format": "uri"
                },
                "version": {
                    "type": "string"
                },
                "binaries": {
                    "type": "object",
                    "properties": {
                        "linux/amd": {
                            "type": "string",
                            "format": "uri"
                        }
                    }
                }
            }
        },
        "peers": {
            "type": "object",
            "properties": {
                "seeds": {
                    "type": "array",
                    "items": {
                        "$ref": "#/$defs/peer"
                    }
                },
                "persistent_peers": {
                    "type": "array",
                    "items": {
                        "$ref": "#/$defs/peer"
                    }
                }
            }
        },
        "apis": {
            "type": "object",
            "properties": {
                "rpc": {
                    "type": "array",
                    "items": {
                        "$ref": "#/$defs/endpoint"
                    }
                },
                "rest": {
                    "type": "array",
                    "items": {
                        "$ref": "#/$defs/endpoint"
                    }
                },
                "grpc": {
                    "type": "array",
                    "items": {
                        "$ref": "#/$defs/endpoint"
                    }
                }
            },
            "additionalProperties": false
        }
    },
    "$defs": {
        "peer": {
            "type": "object",
            "required": [
                "id",
                "address"
            ],
            "properties": {
                "id": {
                    "type": "string"
                },
                "address": {
                    "type": "string"
                },
                "provider": {
                    "type": "string"
                }
            }
        },
        "endpoint": {
            "type": "object",
            "required": [
                "address"
            ],
            "properties": {
                "address": {
                    "type": "string"
                },
                "provider": {
                    "type": "string"
                }
            }
        }
    }
}

=== mililk4/chain-registry/ixo/chain.json
{
    "$schema": "../chain.schema.json",
    "chain_name": "ixo",
    "status": "live",
    "network_type": "mainnet",
    "pretty_name": "IXO",
    "chain_id": "impacthub-3",
    "bech32_prefix": "ixo",
    "slip44": 118,
    "apis": {
        "rpc": [
            {
                "address": "https://rpc-impacthub.keplr.app",
                "provider": "chainapsis"
            },
            {
                "address": "https://proxies.sifchain.finance/api/impacthub-3/rpc",
                "provider": "sifchain"
            },
            {
                "address": "http://18.220.101.192:26657/",
                "provider": "regen"
            }
        ],
        "rest": [
            {
                "address": "https://lcd-impacthub.keplr.app",
                "provider": "chainapsis"
            },
            {
                "address": "https://proxies.sifchain.finance/api/impacthub-3/rest",
                "provider": "sifchain"
            },
            {
                "address": "http://18.220.101.192:1317/",
                "provider": "regen"
            }
        ]
    }
}

=== mililk4/chain-registry/cryptoorg/chain.json
{
    "$schema": "../chain.schema.json",
    "chain_name": "cryptoorg",
    "status": "live",
    "network_type": "mainnet",
    "pretty_name": "Crypto.org",
    "chain_id": "crypto-org-chain-mainnet-1",
    "bech32_prefix": "cro",
    "slip44": 394,
    "apis": {
        "rpc": [
            {
                "address": "https://rpc-crypto-org.keplr.app/",
                "provider": "chainapsis"
            }
        ],
        "rest": [
            {
                "address": "https://lcd-crypto-org.keplr.app/",
                "provider": "chainapsis"
            }
        ]
    }
}

=== mililk4/chain-registry/sentinel/chain.json
{
    "$schema": "../chain.schema.json",
    "chain_name": "sentinel",
    "status": "live",
    "network_type": "mainnet",
    "pretty_name": "Sentinel",
    "chain_id": "sentinelhub-2",
    "bech32_prefix": "sent",
    "slip44": 750,
    "apis": {
        "rpc": [
            {
                "address": "https://rpc-sentinel.keplr.app",
                "provider": "chainapsis"
            }
        ],
        "rest": [
            {
                "address": "https://lcd-sentinel.keplr.app",
                "provider": "chainapsis"
            }
        ]
    }
}

=== mililk4/chain-registry/juno/chain.json
{
    "$schema": "../chain.schema.json",
    "chain_name": "juno",
    "status": "live",
    "network_type": "mainnet",
    "pretty_name": "Juno",
    "chain_id": "juno-1",
    "bech32_prefix": "juno",
    "slip44": 118,
    "apis": {
        "rpc": [
            {
                "address": "https://rpc-juno.itastakers.com",
                "provider": "itastakers"
            }
        ],
        "rest": [
            {
                "address": "https://lcd-juno.itastakers.com",
                "provider": "itastakers"
            }
        ]
    }
}

=== mililk4/chain-registry/starname/chain.json
{
    "$schema": "../chain.schema.json",
    "chain_name": "starname",
    "status": "live",
    "network_type": "mainnet",
    "pretty_name": "Starname",
    "chain_id": "iov-mainnet-ibc",
    "bech32_prefix": "star",
    "slip44": 234,
    "apis": {
        "rpc": [
            {
                "address": "https://rpc-iov.keplr.app",
                "provider": "chainapsis"
            }
        ],
        "rest": [
            {
                "address": "https://lcd-iov.keplr.app",
                "provider": "chainapsis"
            }
        ]
    }
}

=== mililk4/chain-registry/irisnet/chain.json
{
    "$schema": "../chain.schema.json",
    "chain_name": "isisnet",
    "status": "live",
    "network_type": "mainnet",
    "pretty_name": "Irisnet",
    "chain_id": "irishub-1",
    "bech32_prefix": "iris",
    "apis": {
        "rpc": [
            {
                "address": "https://rpc-iris.keplr.app",
                "provider": "chainapsis"
            }
        ],
        "rest": [
            {
                "address": "https://lcd-iris.keplr.app",
                "provider": "chainapsis"
            }
        ]
    }
}

=== mililk4/chain-registry/osmosis/chain.json
{
    "$schema": "../chain.schema.json",
    "chain_name": "osmosis",
    "status": "live",
    "network_type": "mainnet",
    "pretty_name": "Osmosis",
    "chain_id": "osmosis-1",
    "bech32_prefix": "osmo",
    "daemon_name": "osmosisd",
    "node_home": "$HOME/.osmosisd",
    "genesis": "https://github.com/osmosis-labs/networks/raw/main/osmosis-1/genesis.json",
    "codebase": {
        "git_repo": "https://github.com/osmosis-labs/osmosis",
        "version": "v4.0.0",
        "binaries": {
            "linux/amd64": "https://github.com/osmosis-labs/osmosis/releases/download/v4.0.0/osmosisd-4.0.0-linux-amd64",
            "linux/arm64": "https://github.com/osmosis-labs/osmosis/releases/download/v4.0.0/osmosisd-4.0.0-linux-arm64",
            "darwin/amd64": "https://github.com/osmosis-labs/osmosis/releases/download/v4.0.0/osmosisd-4.0.0-darwin-amd64",
            "windows/arm64": "https://github.com/osmosis-labs/osmosis/releases/download/v4.0.0/osmosisd-4.0.0-windows-amd64.exe"
        }
    },
    "peers": {
        "seeds": [
            {
                "id": "8f67a2fcdd7ade970b1983bf1697111d35dfdd6f",
                "address": "52.79.199.137:26656",
                "provider": "cosmostation"
            },
            {
                "id": "00c328a33578466c711874ec5ee7ada75951f99a",
                "address": "35.82.201.64:26656",
                "provider": "cosmostation"
            },
            {
                "id": "cfb6f2d686014135d4a6034aa6645abd0020cac6",
                "address": "52.79.88.57:26656",
                "provider": "cosmostation"
            }
        ],
        "persistent_peers": []
    },
    "apis": {
        "rpc": [
            {
                "address": "https://osmosis.validator.network/",
                "provider": "validatornetwork"
            }
        ]
    }
}

=== mililk4/chain-registry/terra/chain.json
{
    "$schema": "../chain.schema.json",
    "chain_name": "terra",
    "status": "live",
    "network_type": "mainnet",
    "pretty_name": "Terra",
    "chain_id": "columbus-5",
    "bech32_prefix": "terra",
    "apis": {
        "rpc": [
            {
                "address": "http://64.227.72.101:26657",
                "provider": "cryptocrew"
            }
        ],
        "rest": [
            {
                "address": "http://64.227.72.101:1317",
                "provider": "cryptocrew"
            }
        ]
    }
}
